# Generated by Django 2.2.1 on 2019-06-12 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название проекта.', max_length=100)),
                ('img', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название задачи.', max_length=100)),
                ('priority', models.CharField(choices=[('c', 'white'), ('a', 'red'), ('b', 'orange')], default='c', help_text='Приоретет задачи.', max_length=1)),
                ('date_time', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.Project')),
            ],
            options={
                'ordering': ['project', 'name'],
            },
        ),
    ]
